### ISSUE TITLE
Uppercase accent marks in Bold are faux

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/caveat#4]
_Regular:_
<img width="756" alt="screen shot 2017-10-16 at 2 51 02 pm" src="https://user-images.githubusercontent.com/16634089/31608488-91b459e8-b281-11e7-851e-42dfc8a1e5fd.png">

_Bold:_
<img width="716" alt="screen shot 2017-10-16 at 2 51 08 pm" src="https://user-images.githubusercontent.com/16634089/31608492-931657c8-b281-11e7-87cd-d10d542b485b.png">

`brevecomb` has already been fixed in regard to the Cyrillic update in this [PR](https://github.com/googlefonts/caveat/pull/3).

**Comment by alexeiva** [comment]
Fixed in PR #3 
<img width="461" alt="screen shot 2017-10-16 at 8 07 00 pm" src="https://user-images.githubusercontent.com/16634089/31622490-9996fa0e-b2ad-11e7-9e12-a7c3296206b4.png">

**Comment by davelab6** [comment]
Sweet!
