### ISSUE TITLE
Complete language support for all 80%+ languages

### ISSUE THREAD

**Issue by davelab6** [googlefonts/caveat#5]
I'd like to request just a few languages which have over 90% character support and are just missing a few characters :)

| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- | 
| Italian (it) | 108/108 | 100 |  |
| Slovenian (sl) | 112/112 | 100 |  |
| Ukrainian (uk) | 98/98 | 100 |  |
| Estonian (et) | 105/105 | 100 |  |
| Swahili (sw) | 39/39 | 100 |  |
| German (de) | 125/126 | 99 | \u2010 (‐) |
| Czech (cs) | 129/130 | 99 | \u2010 (‐) |
| Lithuanian (lt) | 105/106 | 99 | \u2010 (‐) |
| Norwegian (no) | 104/105 | 99 | \u01ce (ǎ) |
| Romanian (ro) | 101/102 | 99 | \u2010 (‐) |
| Slovak (sk) | 130/131 | 99 | \u2010 (‐) |
| French (fr) | 111/113 | 98 | \u2010 (‐), \u01d4 (ǔ) |
| Russian (ru) | 95/96 | 98 | \u2010 (‐) |
| Indonesian (id) | 73/74 | 98 | \u2010 (‐) |
| Serbian (sr) | 90/91 | 98 | \u2010 (‐) |
| Macedonian (mk) | 84/85 | 98 | \u2010 (‐) |
| Serbian (Latin) (sr-Latn) | 83/84 | 98 | \u2010 (‐) |
| English (en) | 118/121 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| English (United Kingdom) (en-GB) | 118/121 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Spanish (es) | 127/130 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Spanish (Latin America) (es-419) | 127/130 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Dutch (nl) | 107/110 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Polish (pl) | 123/126 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Portuguese (pt) | 121/124 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Turkish (tr) | 127/130 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Catalan (ca) | 126/129 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Danish (da) | 107/110 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Hungarian (hu) | 130/133 | 97 | \u2052 (⁒), \u27e8 (⟨), \u27e9 (⟩) |
| Latvian (lv) | 106/109 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Portuguese (Portugal) (pt-PT) | 121/124 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Swedish (sv) | 106/109 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Afrikaans (af) | 105/108 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Icelandic (is) | 100/103 | 97 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Filipino (fil) | 94/97 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Croatian (hr) | 86/89 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Azerbaijani (az) | 94/97 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Malay (ms) | 80/83 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Albanian (sq) | 84/87 | 96 | \u2010 (‐), \u2032 (′), \u2033 (″) |
| Bulgarian (bg) | 88/92 | 95 | \u2010 (‐), \u2033 (″), \u0463 (ѣ), \u046b (ѫ) |
| Finnish (fi) | 155/162 | 95 | \u2010 (‐), \u021f (ȟ), \u0292 (ʒ), \u01e5 (ǥ), \u01e7 (ǧ), \u01e9 (ǩ), \u01ef (ǯ) |
| Uzbek (uz) | 83/87 | 95 | \u2010 (‐), \u2032 (′), \u2033 (″), \u02bb (ʻ) (or its correct equivalent) |
| Kyrgyz (ky) | 96/103 | 93 | \u2010 (‐), \u04a2 (Ң), \u04ae (Ү), \u04af (ү), \u04ca (ӊ), \u04e8 (Ө), \u04e9 (ө) |
| Mongolian (mn) | 61/70 | 87 | \u2010 (‐), \u0497 (җ), \u04af (ү), \u2032 (′), \u2033 (″), \u04bb (һ), \u04ca (ӊ), \u04d9 (ә), \u04e9 (ө) |
| Kazakh (kk) | 98/115 | 85 | \u2010 (‐), \u0492 (Ғ), \u0493 (ғ), \u049a (Қ), \u049b (қ), \u04a2 (Ң), \u04a3 (ң), \u04ae (Ү), \u04af (ү), \u04b0 (Ұ), \u04b1 (ұ), \u04ba (Һ), \u04bb (һ), \u04d8 (Ә), \u04d9 (ә), \u04e8 (Ө), \u04e9 (ө) |
| Vietnamese (vi) | 112/157 | 71 | \u2010 (‐), \u2032 (′), \u2033 (″), \u01a0 (Ơ), \u01a1 (ơ), \u1ea1 (ạ), \u1ea3 (ả), \u1ea5 (ấ), \u1ea7 (ầ), \u1ea9 (ẩ), \u1eab (ẫ), \u1ead (ậ), \u1eaf (ắ), \u01af (Ư), \u01b0 (ư), \u1eb1 (ằ), \u1eb3 (ẳ), \u1eb5 (ẵ), \u1eb7 (ặ), \u1ebb (ẻ), \u1ebf (ế), \u1ec1 (ề), \u1ec3 (ể), \u1ec5 (ễ), \u1ec7 (ệ), \u1ec9 (ỉ), \u1ecf (ỏ), \u1ed1 (ố), \u1ed3 (ồ), \u1ed5 (ổ), \u1ed7 (ỗ), \u1ed9 (ộ), \u1edb (ớ), \u1edd (ờ), \u1edf (ở), \u1ee1 (ỡ), \u1ee3 (ợ), \u1ee7 (ủ), \u1ee9 (ứ), \u1eeb (ừ), \u1eed (ử), \u1eef (ữ), \u1ef1 (ự), \u1ef5 (ỵ), \u1ef7 (ỷ) |

**Comment by alexeiva** [comment]
Added Latin CLDR glyphs but Vietnamese in https://github.com/alexeiva/caveat/commit/b9a36f40f62d0e09ee6c7ea40cd6901f2bed1661
All mentioned Cyrillic-based languages are covered in the Cyrillic Plus/Pro update

<img width="441" alt="screen shot 2017-12-15 at 5 43 48 pm" src="https://user-images.githubusercontent.com/16634089/34044754-b85015de-e1bf-11e7-9191-ab13b02e3e1b.png">

**Comment by davelab6** [comment]
Awesome, thank you!
